name: SnowballDebuff
version: 1.0.0
main: SnowBallDebuff\Main
api: 5.0.0
author: zFrozead0s
commands:
  snowball:
    description: "Obtén una bola de nieve"
    usage: "/snowball"
    permission: snowballdebuff.cmd

permissions:
  snowballdebuff.cmd:
    default: true
